name: "Repository stats"

description: "Compiles git statistics for a repository"

inputs:
  from-date:
    description: "The start date for the statistics"
    required: true
    default: "2021-01-01"

runs:
  using: "composite"
  steps:
    - name: Fetch statistics
      run: |
        echo "Fetching statistics from: $FROM_DATE... "

        # Fetch commit stats
        ## Source: https://gist.github.com/eyecatchup/3fb7ef0c0cbdb72412fc
        CHANGES="$(git log --pretty=tformat: --numstat --since=$FROM_DATE | awk '{inserted+=$1; deleted+=$2; delta+=$1-$2; ratio=deleted/inserted} END {printf "Commit stats:\n- Lines added (total)....  %s\n- Lines deleted (total)..  %s\n- Total lines (delta)....  %s\n- Add./Del. ratio (1:n)..  1 : %s\n", inserted, deleted, delta, ratio }' -)"

        # Print output
        echo "$CHANGES"
      shell: bash
      env:
        FROM_DATE: ${{ inputs.from-date }}
